### ISSUE TITLE
Suggestion: Being able to setup a role with the permission of deleting and editing ANY ticket replies.

### ISSUE THREAD

**Issue by Hector1801** [Dragory/modmailbot#663] opened 2021-09-23 16:11 UTC
We really need a setting that'd allow people with a certain role to **delete** and **edit** ANY ticket reply, even if it wasn't they who sent the reply to the user.

This'd be really useful for when the Moderator who sent the reply is not available to edit/delete it at the moment.

**Comment by DarkView** [comment] 2023-09-21 19:41
Duplicate of #520

**Closed by DarkView** 2023-09-21 19:41 UTC
