### ISSUE TITLE
any immediate future to add reusing discord attachment

### ISSUE THREAD

**Issue by maidos** [Dragory/modmailbot#197] opened 2018-11-26 21:44 UTC
using discord attachment instead of rehosting which is a huge burden on some host like glitch.com 
https://i.imgur.com/wLmKwzL.png

**Comment by maidos** [comment] 2018-11-26 21:45
if theres money incentive i would gladly pay.

**Comment by maidos** [comment] 2018-11-29 09:41
even with a paid host its still rather inefficent to rehost when you can use reuse discord cdn attachment files. Eventually the files will get larger so you eventually have to get largher file space and the solution to upgrade is just not a good idea

**Comment by Dragory** [comment] 2019-01-19 13:49
Closing as duplicate of #158. Please follow that issue for any updates.

**Closed by Dragory** 2019-01-19 13:49 UTC
