### ISSUE TITLE
TypeError: Cannot read property 'get' of Undefined 

### ISSUE THREAD

**Issue by wc3717** [Dragory/modmailbot#278] opened 2019-05-10 08:14 UTC
Keep getting this error recently. I'm not sure what is causing it as it started bugging the bot. I tried installing a clean version but no luck: https://i.imgur.com/VEX6Ype.png

**Comment by wc3717** [comment] 2019-05-10 12:05
Getting a channel.update error now.

**Comment by Dragory** [comment] 2019-05-10 13:51
Hmm, the error in the image seems to be stemming from pretty deep in the Eris lib. Could be related to the API issues Discord had earlier today. Are these errors random or do they happen e.g. every time the bot is started?

**Comment by EnzoDevelop** [comment] 2019-05-10 19:51
can reproduce https://i.imgur.com/eIx6yAK.png

**Comment by EnzoDevelop** [comment] 2019-05-10 19:51
appears to be stemming from the websocket
possible an issue with eris

**Comment by wc3717** [comment] 2019-05-11 07:00
These errors are random @Dragory they happen every couple of hours. One person suggested it could be the special Developer Licence channels, like the special updates channel so we removed the bots perms to see those channels but no luck.

**Comment by jackieboy201** [comment] 2019-05-11 08:13
I got this from someone that thinks they know how to fix it by installing the new dev branch to the bot:
https://i.imgur.com/0ObwQm2.png https://i.imgur.com/uYX6Qko.png https://i.imgur.com/bg5rZ4W.png

**Comment by Dragory** [comment] 2019-06-04 22:11
This should now be fixed in v2.21.2. Sorry for the delay, and thank you for the heads-up and extra context!

**Closed by Dragory** 2019-06-04 22:11 UTC
