### ISSUE TITLE
Error: Cannot find module '/home/container/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'

### ISSUE THREAD

**Issue by Director119** [Dragory/modmailbot#217] opened 2019-01-30 23:20 UTC
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/home/container/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/container/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (/home/container/node_modules/knex/lib/dialects/sqlite3/index.js:57:12)
    at Client_SQLite3.initializeDriver (/home/container/node_modules/knex/lib/client.js:250:26)
    at Client_SQLite3.Client (/home/container/node_modules/knex/lib/client.js:108:10)
    at new Client_SQLite3 (/home/container/node_modules/knex/lib/dialects/sqlite3/index.js:42:20)

**Comment by Dragory** [comment] 2019-01-31 08:14
Try deleting your node_modules folder and running `npm install` again. If that doesn't work, try downgrading to Node.js 8 and then deleting your node_modules folder and running `npm install`.

**Comment by Director119** [comment] 2019-01-31 19:40
Is there a different way to do it, without downgrading to node.js 8. Because the problem comes when I go to host the bot. The bot works fine in visual studio code...

**Comment by Director119** [comment] 2019-02-02 02:45
![image](https://user-images.githubusercontent.com/45493702/52158861-ec234980-269c-11e9-9367-0fb127fe8b35.png)

**Comment by Dragory** [comment] 2019-02-02 07:36
Either way, try deleting your node_modules folder and running `npm install` again. And if that doesn't work, I'd still try with a different version of Node.js.

Note that this isn't an issue with the bot, it's a version mismatch of some sort with some of the dependencies, so I'm mostly just telling you how it usually fixes itself.

**Comment by Director119** [comment] 2019-02-02 09:05
![image](https://user-images.githubusercontent.com/45493702/52162300-088da900-26d2-11e9-9c0e-31c0b95252b7.png)

**I understand what you mean. But I am trying to say is...
The bot works fine in Visual Studio Coding, but when I go to host the bot, the errors appears.**

**Comment by DieselGaming** [comment] 2019-02-09 13:42
If you are using the hosting site `Heroku` then this bot will most likely not work.
`Heroku` does not support sqlite3, so it won't start.

**Comment by Director119** [comment] 2019-02-17 22:51
Sorry for the late reply...was on vacation..
yes! ruing it on a console

**Comment by danielpmc** [comment] 2019-02-18 23:42
Hello,
I am the host that @Director119 uses. 

We are using the pterodactyl game panel using a custom docker image i created ( https://hub.docker.com/r/danielpmc/discordnode8 ) 
upon trying to start the bot the error is: 
`:/home/container$ node .
Knex: run
$ npm install sqlite3 --save
Error: Cannot find module '/home/container/node_modules/sqlite3/lib/binding/node-v57-linux-x64/node_sqlite3.node'
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/container/node_modules/sqlite3/lib/sqlite3.js:4:15)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Client_SQLite3._driver (/home/container/node_modules/knex/lib/dialects/sqlite3/index.js:57:12)
    at Client_SQLite3.initializeDriver (/home/container/node_modules/knex/lib/client.js:250:26)
    at Client_SQLite3.Client (/home/container/node_modules/knex/lib/client.js:108:10)
    at new Client_SQLite3 (/home/container/node_modules/knex/lib/dialects/sqlite3/index.js:42:20)`
If you have any information on how this could be fixed please let me know!

Thanks,
Dan

**Comment by Director119** [comment] 2019-02-20 09:59
@Dragory Can you please let us know what to do?

**Comment by Dragory** [comment] 2019-02-23 13:36
Hey! Sorry, these sqlite installation issues are fairly random and are not strictly related to the bot - it's more an issue with npm and how the sqlite package is installed. The problem could be caused by a combination of things, including your platform (or what Node.js sees as the platform within the Docker image) and Node.js version (which seems to be 8 here), but what the error is saying is that it can't find the proper binaries/bindings for the Node.js version that's being used. Normally, these bindings would get downloaded or compiled during `npm install`, but that doesn't seem to be happening correctly in this case.

Some things to try/consider:
1) If you're installing the packages (`npm install`) using one installation of Node.js (e.g. your local installation), and then running the bot using another (e.g. the Docker one), that will most likely fail. You need to run `npm install` and `npm start` with the same Node.js installation (and if you e.g. update Node.js, delete the old `node_modules` folder and run `npm install` again)
2) Related to point 1, don't e.g. copy your node_modules folder from your PC to the server. Always run `npm install` on the same setup where you run the bot.
3) Try reinstalling everything with `npm install`. Make sure you delete your old `node_modules` folder before doing this.

**Comment by danielpmc** [comment] 2019-02-25 01:30
Hey
Thanks for your help its all fixed now!

**Comment by Director119** [comment] 2019-02-25 05:01
Yep. Thanks alot!!!

**Comment by Dragory** [comment] 2019-02-25 09:23
👍 Glad you got it working!

**Closed by Dragory** 2019-02-25 09:23 UTC

**Comment by ZachZeop** [comment] 2019-04-29 06:29
I know this was a while ago, and closed. But I am encountering the exact same issue and also using Pterodactyl. Any help would be very much appreciated.
