### ISSUE TITLE
Logs On Website

### ISSUE THREAD

**Issue by ieuangol** [Dragory/modmailbot#181] opened 2018-10-19 21:09 UTC
Hey so I'm hosting my bot on glitch.com and my website is on 000webhost how would I set logs to upload to my website?

**Comment by Huskydog9988** [comment] 2018-10-29 20:51
This is currently not a feature, but hopefully will be soon. You can track this 
Duplicate of #158

**Comment by maidos** [comment] 2018-10-29 21:45
ah not dublicate since my original ticket was asking the bot to not rehost attachment files due to having limited file space on my current host which is glitch.com 
for me its daily chore to delete attachment files. 
That apply the same thing with the logs files aswell as it quickly consume space.

**Comment by maidos** [comment] 2018-10-30 21:06
what i currently struggle with attachment rehost
https://i.imgur.com/K5Pcbb2.png

**Comment by Huskydog9988** [comment] 2018-10-31 14:55
Oh, since your using glitch you will have to edit the code a bit I believe, not just the config. I don’t know much about glitch hosting so I’m pretty much useless

**Comment by Dragory** [comment] 2019-01-19 13:46
Closing as duplicate of #45

**Closed by Dragory** 2019-01-19 13:46 UTC
