### ISSUE TITLE
Website logs.

### ISSUE THREAD

**Issue by noah-beep** [Dragory/modmailbot#540] opened 2021-01-25 12:50 UTC
The website logs don't work.

**Comment by mesub7** [comment] 2021-01-25 17:38
Make sure the bot is running when trying to view log links. If the logs still don't work, the problem is usually that the log viewer's port needs to be forwarded. If you're running the bot on your own PC, check https://portforward.com/ for instructions on how to do this. If you're running the bot on a VPS, your host can help you get started. The port that needs to be forwarded in Modmail Bot's case (assuming default settings) is TCP **8890**.

If you're still running into issues the come find us in [the support server.](https://discord.gg/vRuhG9R)

**Comment by Dragory** [comment] 2021-01-30 12:15
Closing this. If you're still experiencing this issue, please join the support server and we can try to work it out there!

**Closed by Dragory** 2021-01-30 12:15 UTC
