### ISSUE TITLE
Suggestion : 

### ISSUE THREAD

**Issue by ItzzJma** [Dragory/modmailbot#598] opened 2021-04-26 18:13 UTC
https://media.discordapp.net/attachments/809930157016088606/836227708027142224/unknown.png

https://cdn.discordapp.com/attachments/809930157016088606/836227979960123422/unknown.png

can u add a same function like this?

also can u also add when someone close the thread, it send a message (customizable) saying like "thank u for contacting us, feel free to ask if u have more questions,"

**Comment by GeekCornerGH** [comment] 2021-04-27 16:42
First suggestion, its a good idea. For close message, there is actually an option to add in config.ini

**Comment by DarkView** [comment] 2023-09-21 19:32
Duplicate of #357

**Closed by DarkView** 2023-09-21 19:32 UTC
