### ISSUE TITLE
Temporarly Stop/Autorespond Close Incoming Messages

### ISSUE THREAD

**Issue by JaymeiF** [Dragory/modmailbot#622] opened 2021-06-03 19:06 UTC
Imagine if you will a sudden influx of around 11k people who all feel like messaging Mod Mail.

Simple Answer - Turn off the bot.
Advanced - Global command to "turn off" incoming DM.
Complex - Accept messages, autorespond and close.

Some/all/none of this may already be available or not going to happen but would be nice to see.

**Comment by DarkView** [comment] 2023-09-21 19:34
Duplicate of #267

**Closed by DarkView** 2023-09-21 19:34 UTC
