### ISSUE TITLE
Log Ability

### ISSUE THREAD

**Issue by JustPoppy** [Dragory/modmailbot#44] opened 2017-11-26 12:24 UTC
Well, it would be nice to explain on how to set up LOGS and ports. Because, we do not understand, and I don't understand how can I enable that on my VPS (Ubuntu)..

**Comment by Dragory** [comment] 2017-11-26 12:28
Logs are saved in `<bot folder>/logs`. The default port is 8890, but can be configured with the config option `port`. After that, the only thing you need to do is ensure that port is open so that the logs can be accessed over the web.

**Comment by EvilWalks** [comment] 2017-12-31 03:50
I'm actually having some real difficulty with this also. As it stands, I'm stuck with logs I can't access, and attachments no one can view, because I can't seem to work out what I'm doing with this function. :(

Definitely feeling pretty silly. 

In config.json I have my home IP set (since I'm running it off my local PC for now) and the port set as 8892. This is all port forwarded on the router. However, logs, and attachments are displaying an IP address that is different to what I've input anyway. 

I'm really confused currently.

**Comment by Dragory** [comment] 2017-12-31 18:15
Hey, could you post a picture (or paste) of your config with the token blocked/cropped out? @EvilWalks

**Comment by EvilWalks** [comment] 2018-01-01 04:21
Hi @Dragory 

Here's a screen... didn't know what I should hide and not, so did all the ID's too. 

https://imgur.com/a/cWBMD

Despite that config, the URL's produced by the bot within our inbox server all have a different address, as follows: 

http://223.165.64.117:8892/logs/8cc83042e39eec626a99ec9a9ea30cbc

Thanks for any help you can provide. I feel like it's going to something simple that I've overlooked. Which is why I feel so stupid about it all.

**Comment by EvilWalks** [comment] 2018-03-06 03:41
@Dragory still having issues, but it's changed. Doesn't instantly open a page saying unavailable. Instead times out after 20 seconds or so. I'm pretty sure my windows and router firewalls are setup correctly to allow it through. 

It displays the correct IP address now. 

And yeah, was definitely editing the correct config file.

**Comment by Dragory** [comment] 2018-03-06 18:37
If the displayed IP (and port) is correct, I'm inclined to say the problem is related to your firewall/router/isp. Can't think of anything that could be causing it on the bot's side (without errors anyway).

**Comment by sporkwitch** [comment] 2018-04-21 00:53
@EvilWalks @JustPoppy are either of you still having difficulties?  If not, let's try to get this issue closed.

**Comment by sporkwitch** [comment] 2018-05-17 00:58
@Dragory can probably close this one

**Closed** 2018-06-03 11:15 UTC
Labels: help request
