### ISSUE TITLE
Bot shutting down

### ISSUE THREAD

**Issue by JustxMeg** [Dragory/modmailbot#90] opened 2018-07-03 16:08 UTC
![image](https://user-images.githubusercontent.com/7931828/42231561-1cb7e2f8-7eec-11e8-8bcf-077747b59e91.png)
How can I fix this?

**Comment by Dragory** [comment] 2018-07-05 08:13
It looks like a modmail thread's channel was deleted before/while the thread was being closed. Does this happen every time you start the bot, or on some specific action? And can you reproduce it, or did it only happen once?

**Comment by JustxMeg** [comment] 2018-07-05 18:20
Hey,

It happens only when we close a channel. So I moved it to another folder, but the older logs aren't being opened again, is there a way to get them from the server and put them local on my computer?

**Comment by JustxMeg** [comment] 2018-07-05 20:31
New issue... https://oowoo.club/gockzjmp.jpg

**Comment by JustxMeg** [comment] 2018-07-07 18:42
[NOTE] Creating new thread channel dropbox-0001
Closing thread 3c9463e4-b10c-4c00-945e-327f1598c91f
Deleting channel 465225585317249035
[INFO] Auto-closing thread with Dropbox#0001 because the channel no longer exists
Error: DiscordRESTError [10003]: Unknown Channel
Again, when the thread was there.

**Comment by Dragory** [comment] 2018-07-07 20:03
That looks weird. The bot said it's auto-closing the thread that you just closed, and it shouldn't do that unless you had an unclosed thread and you deleted its channel.

I could see some network lag causing a race condition, leading to this. Do you (or the server) generally have any network issues (slowness, etc.) with Discord?

**Comment by JustxMeg** [comment] 2018-07-07 20:16
Hey,

Server is working fine for me, only had problems with the npm today after a reboot, but stuff worked good before.

Van: Miikka <notifications@github.com> 
Verzonden: zaterdag 7 juli 2018 22:03
Aan: Dragory/modmailbot <modmailbot@noreply.github.com>
CC: Dropbox <sir.mark1994@gmail.com>; Author <author@noreply.github.com>
Onderwerp: Re: [Dragory/modmailbot] Bot shutting down (#90)

 

That looks weird. The bot said it's auto-closing the thread that you just closed, and it shouldn't do that unless you had an unclosed thread and you deleted its channel.

I could see some network lag causing a race condition, leading to this. Do you (or the server) generally have any network issues (slowness, etc.) with Discord?

**Comment by JustxMeg** [comment] 2018-07-07 20:17
Hey,

Server is working fine for me, only had problems with the npm today after a reboot, but stuff worked good before.

**Comment by JustxMeg** [comment] 2018-07-08 10:50
It happens also, when I close other threads.

**Comment by JustxMeg** [comment] 2018-07-09 10:36
A fix would be great, we can't keep restarting the bot. @Dragory

**Comment by JustxMeg** [comment] 2018-07-09 15:39
It's trying to auto-close a thread when I use the /close command.

**Comment by JustxMeg** [comment] 2018-07-11 19:10
Running it with pm2 now.

**Comment by Dragory** [comment] 2018-07-11 19:53
I'd love to fix the issue you're having, but you're the first person to report this as far as I know, and I'm not sure how to reproduce your issue. If you'd like to experiment a bit to find a proper solution (instead of auto-restarting every time a thread is closed), could you do a fresh modmail install and *only* set the token, and see if that works?

**Comment by JustxMeg** [comment] 2018-07-11 19:56
Hey, then it works fine.

**Comment by Dragory** [comment] 2018-07-11 20:21
Hmm, can you post your config file (without the token)?

**Comment by JustxMeg** [comment] 2018-07-13 16:48
https://oowoo.club/55e0eymg.png getting this now, on a new one.

Config:
`{
  "token": "",
  "mailGuildId": "458910463070044161",
  "mainGuildId": "458910463070044161",
  "logChannelId": "462666043941191680",
  "prefix": "/",
  "newThreadCategoryId": "462661219824697426",
  "snippetPrefix": "/",
  "typingProxy": "true",
  "typingProxyReverse": "true",

  "status": "Hulp nodig? Stuur een DM!",
  "responseMessage": "Bedankt voor je bericht, iemand van de staff zal je zo snel mogelijk van een antwoord voorzien."
}`

**Comment by JustxMeg** [comment] 2018-07-19 18:37
Best support ever, not.

**Comment by Dragory** [comment] 2018-07-19 21:17
I'm currently on vacation, so I'm not answering github issues. You could do with a less entitled attitude...

**Comment by JonasPardon** [comment] 2018-07-20 09:58
Can you be any more self-entitled here. This is obviously an issue that Dragory can't fix just like that if he can't reproduce it himself. Dragory owes nothing to anybody here.
I suggest you make your own bot if you think this isn't sufficient.

**Comment by JustxMeg** [comment] 2018-07-21 15:02
@JonasPardon smh, don't make a bot if you don't give support. :/

Like, he's on a holiday, so it's ok now and now I wait.

**Comment by JonasPardon** [comment] 2018-07-21 15:08
Don't be so dense. He's not hosting it or anything. 
He just likes coding something and putting it up here for public use, that still doesn't mean he owes you anything at all.

**Comment by JustxMeg** [comment] 2018-07-26 18:20
Can't open attachments too....

**Comment by Dragory** [comment] 2018-07-27 16:01
I still haven't been able to reproduce the issues you mention in this thread (except the EADDRINUSE one - that's usually because there's an old bot process running in the background when you run a new one, so it's trying to use the same port).

For the original channel issues:
Can you make a fresh installation of the bot with only the required config options, see if it works, and then keep adding your old config options and restarting until you start seeing the channel issues again? If you get the EADDRINUSE error, make sure you only have 1 bot process running (check Task Manager for old node.exe processes).

For the attachment problem:
I'll need more details on this. What exactly happens? Is there a black page, a browser error, an error in the console?

**Comment by JustxMeg** [comment] 2018-07-27 19:40
Fresh install, default config, on a other folder gives the error I said earlier, somehow. PM2 works fine for me.

ERR_EMPTY_RESPONSE for the attachment issue.

**Comment by Dragory** [comment] 2018-07-27 20:00
You're getting the EADDRINUSE error even when there are no other `node.exe`s running? The error only means that the port (8890) is already in use by another process, so that other process needs to be shut down first.

**Comment by JustxMeg** [comment] 2018-07-27 21:06
Even on a other folder? :S And when I stop the bot I cant start it...

**Comment by Dragory** [comment] 2018-07-27 21:14
Yeah, the port needs to be unique on the same machine, regardless of the folder. You can use the `port` config option to change the port to something else in the new folder, e.g. `9000`. When you say you "can't start it", are you getting the EADDRINUSE error or something else?

**Comment by JustxMeg** [comment] 2018-07-28 17:17
Not getting a error now for the second one, but I'm scared to shutdown the main one now...

**Comment by Dragory** [comment] 2018-07-30 14:41
Okay, what if you start moving over your config options one at a time from the main one? Is there a point where it stops working?

**Comment by JustxMeg** [comment] 2018-07-30 15:35
No, but when I stop it, does it keep running a node?

**Comment by Dragory** [comment] 2018-07-30 16:01
When you close the window, it *should* close the Node.exe process as well, though I remember there was a bug at one point where it didn't. I recommend confirming it's actually shut down in task manager.

**Comment by JustxMeg** [comment] 2018-08-03 09:24
Stuff works fine now, but attachments doesn't seem to be saved on the vps?

**Comment by Dragory** [comment] 2018-08-04 18:58
Are the attachments not being saved at all, or are the attachment links not working? Does this happen on both the old installation and a clean installation?

**Comment by JustxMeg** [comment] 2018-08-04 19:47
The links aren't working and the new version isn't tested anymore, but the old keeps crashing without pm2.

**Comment by Dragory** [comment] 2018-08-04 20:02
And there's also nothing in the bot's `attachments` folder (in the bot's folder)?

**Comment by JustxMeg** [comment] 2018-08-04 20:17
There is, and I'm scared too reinstall it because we can't lose the logs.

**Comment by JustxMeg** [comment] 2018-08-04 20:25
Also on the other bot, same issue.

**Comment by Dragory** [comment] 2018-08-04 21:45
So what happens when you try to open an attachment link?

**Comment by JustxMeg** [comment] 2018-08-07 19:15
Attachments arent getting an extension on the vps when they are saved.

**Comment by Dragory** [comment] 2018-08-07 19:18
That is intended, the extension and mime type are based on the attachment's data from Discord and should be served properly via the URL. When you get `ERR_EMPTY_RESPONSE`, is there an error in the console at the same time?

**Comment by JustxMeg** [comment] 2018-08-07 19:24
Yeah, something with mime. Running it now with npm because we cant have crashes.

**Comment by Dragory** [comment] 2018-08-07 20:30
What's the exact error?

**Comment by JustxMeg** [comment] 2018-08-08 16:30
![image](https://user-images.githubusercontent.com/7931828/43850777-26b1dc78-9b39-11e8-848e-3a9d49c7d7e8.png)
Here you go.

**Comment by Dragory** [comment] 2018-08-08 18:51
I released a new update yesterday that also updated that specific like. Can you give it a try?

**Comment by JustxMeg** [comment] 2018-08-08 19:12
Can you tell me how I update it without losing stuff?

**Comment by Dragory** [comment] 2018-08-09 18:04
I'll write some update instructions in the README tomorrow. The TL;DR is:

1. Shut down the bot
2. Take a backup of the `db/data.sqlite` and `config.json` files and the `attachments` folder
3. Download the latest release from [the releases page](https://github.com/Dragory/modmailbot/releases) and extract the files over the old ones (if you're on Mac and it asks you whether to *Replace* or *Merge*, pick *Merge*)
4. Start the bot. If any of the files backed up before went missing for some reason, restore them from the backup.

**Comment by Dragory** [comment] 2018-08-09 21:24
Yes - snippets, logs, and other bot data (apart from attachments) are kept in `db/data.sqlite`. That's the most important file to back up!

**Comment by JustxMeg** [comment] 2018-08-10 06:34
Amazing! Are now also able to make snippets to be anonymous?

**Comment by Dragory** [comment] 2018-08-11 12:40
You seem to have `"closeMessage:"` twice there. It should be just:

```
"closeMessage": "Bedankt dat je contact...",
```

**Comment by JustxMeg** [comment] 2018-08-11 12:48
Alright, everything seems to work now! Thanks so much, you can close this one.

**Closed** 2018-08-11 14:33 UTC
