### ISSUE TITLE
Suggestion: Whitelist Bots

### ISSUE THREAD

**Issue by RocketManKian** [Dragory/modmailbot#729] opened 2022-08-20 13:59 UTC
Hey there!

I'd love for there to be an optional option to whitelist a certain bot so that Modmail will listen for messages from it.

This would be useful since I have a bot that sends the New Thread command when a user enters information into a form, but right now Modmail doesn't react to it whatsoever.

Thanks!

**Comment by DarkView** [comment] 2023-09-21 19:47
Duplicate of #660

**Closed by DarkView** 2023-09-21 19:47 UTC
