### ISSUE TITLE
[Suggestion] Allow admins to edit/delete other staff replies

### ISSUE THREAD

**Issue by Retr0-01** [Dragory/modmailbot#539] opened 2021-01-23 10:34 UTC
I believe trusted people should have complete control over the bot when it comes to managing threads.

**Comment by Dragory** [comment] 2021-01-30 12:14
Agreed - this is something I'm looking to add in the future, but it will require a more robust permission system first to differentiate between moderators and admins/owners. I'll update here when there's been more work on that.

**Comment by Retr0-01** [comment] 2021-01-31 07:39
Awesome! Thanks in advance.

**Comment by DarkView** [comment] 2023-09-21 19:25
Duplicate of #520

**Closed by DarkView** 2023-09-21 19:25 UTC
Labels: feature request
