### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by teheim** [Dragory/modmailbot#592] opened 2021-04-07 21:04 UTC
Add member to ticket. 
Adds and extra member to the DM's 

This will be useful in tickets where multiple people needs to talk together. 
(Dms sent to the bot will also send to the rest of the users)

(Should probably also include a command that hides messages to the other users when sent such as "!hide (message)"

!adduserdm <User Id>

**Comment by k9lego** [comment] 2021-04-10 18:26
This would be very helpful, support!

**Comment by DarkView** [comment] 2023-09-21 19:31
Duplicate of #311

**Closed by DarkView** 2023-09-21 19:31 UTC
